const add = (a, b) => {
    return new Promise((resolve, reject) => {
        setTimeout(() => {
            resolve(a + b)
        }, 2000)
    })
}


const addAsync = async (a, b) => {
    if (a < 0 || b < 0) throw new Error('a and b must be positive')
    const sum = await add(a, b);
    return sum;

}

addAsync(-2, 3).then(result => {
    console.log(result);
}).catch(err => console.log(err));